// import React, { useState, useEffect } from 'react';
// import axios from 'axios';
// import { useLocation } from 'react-router-dom';
// import jspdf from 'jspdf';
// import 'jspdf-autotable';
// import companyLogo from '../../assets/sidebar-logo.png';
// import DownloadIcon from '@mui/icons-material/Download';
// import IconButton from '@mui/material/IconButton';


// const Userlist = () => {
//     const location = useLocation();
//     const path = location.pathname.split('/')[1];
//     const [dataList, setDataList] = useState([]);
  
//     const headers = [
//       'Supplier',
//       'Item',
//       'Quantity Ordered',
//     ];
  
//     const fetchOrders = async () => {
//         const response = await axios.get(`http://localhost:3000/api/order`);
//         if (response.data.success) {
//           return response.data.data;
//         } else {
//           throw new Error('Error fetching data');
//         }
//       };
      
//       const { data, error, isLoading, isError } = useQuery('orders', fetchOrders);
      
//       useEffect(() => {
//         if (data) {
//           setDataList(data);
//         }
//       }, [data]);
  
//     function generatePDF(orders) {
//       const doc = new jspdf();
//       const tableRows = [];
  
//       orders.forEach((order, index) => {
//         const orderData = [
//           order.supplier,
//           order.item,
//           order.quantity,
//         ];
//         tableRows.push(orderData);
//       });

//     const date = new Date().toLocaleDateString('en-US', {
//       day: 'numeric',
//       month: 'short',
//       year: 'numeric',
//     });

//     const margin = 14; 
//     const logoWidth = 30; 
//     const logoHeight = 20; 
//     const maxWidth = 290; 
//     const textLines = doc.splitTextToSize(
//     `This report provides a comprehensive overview of the quantity of items ordered from each supplier. It is an essential tool for effective inventory management and procurement planning. By meticulously documenting and organizing this data, we can ensure optimal supply chain operations, facilitate informed decision-making processes, and promote the overall efficiency and productivity of the business.`,
//     maxWidth
//     );
//     const textParagraph = textLines.join('\n');
   
//     doc.addImage(companyLogo, 'PNG', doc.internal.pageSize.width - margin - logoWidth, margin, logoWidth, logoHeight);

   
//     doc.setFontSize(10).setFont('helvetica').text('Nevil Nutri Feeds Pvt.Ltd', margin, margin + 10);
//     doc.text('No:241, Rdawana', margin, margin + 15);
//     doc.text('Henagama Rd', margin, margin + 20);
//     doc.text('Gampaha', margin, margin + 25);
//     doc.text('Sri Lanka', margin, margin + 30);

//     doc.setFontSize(10).text(`Date: ${date}`, margin, margin + 35);

   
//     doc.setFontSize(20).setTextColor(56, 119, 91).setFont('helvetica', 'bold').text('Animal Registry Report', margin, 70);

   

    
//     doc.setFontSize(10).setFont('helvetica', 'normal').setTextColor(0, 0, 0).text(
//       textParagraph,
//       margin,
//       80,
//       { maxWidth: maxWidth } 
//     );

 
//     doc.autoTable(headers, tableRows, {
//         styles: { fontSize: 10 },
//         startY: 100,
//         headerStyles: { fillColor: [31, 41, 55] },
//       });


//     doc.setFontSize(10).setTextColor(200, 200, 200).text(`Report generated by Veterinary Management System`, margin, doc.internal.pageSize.height - 10);

  
//     doc.save('Animal-Registry-Report.pdf');
//   }

//   return (
//     <div>
//       <IconButton
//         onClick={() => {
//           generatePDF(dataList);
//         }}
//         className="bg-gray-800 text-center hover:bg-gray-600 text-white font-bold py-2 px-4 rounded cursor-pointer lg:mt-0 mt-3"
//       >
//          <DownloadIcon/>
        
//       </IconButton>
//     </div>
//   );
// };

// export default OrderReport;
